{% set name = "gf-kernel" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gf_kernel-{{ version }}.tar.gz
  sha256: a3e499580cb1b5c77a8e2078f2ba8a92db58af78d99c3b5d5a003be767a46145

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - ipykernel >=5.1.0
    - ipython >=7.2.0
    - ipywidgets >=7.4.2
    - jupyter >=1.0.0
    - jupyter_client >=5.2.4
    - python >={{ python_min }}

test:
  imports:
    - gf_kernel
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/KWARC/gf_kernel
  summary: Simple example kernel for GF
  license_file: LICENSE
  license: GPL-3.0-only
  license_family: GPL

extra:
  recipe-maintainers:
    - step21
